-- MySQL Script generated by MySQL Workbench
-- Fri Jun 22 10:06:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema trade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trade` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema backup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backup` DEFAULT CHARACTER SET utf8 ;
USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `age` TINYINT(4) NULL,
  `sex` VARCHAR(45) NULL,
  `creatAt` DATETIME NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`.`shipping_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`shipping_address` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` BIGINT UNSIGNED NOT NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `trade` ;

-- -----------------------------------------------------
-- Table `trade`.`trade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade`.`trade` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` BIGINT UNSIGNED NOT NULL,
  `product` VARCHAR(45) NULL,
  `number` INT NULL,
  `price` DECIMAL(10,2) NULL,
  `creatAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `backup` ;

-- -----------------------------------------------------
-- Table `backup`.`backup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`backup` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` TEXT NULL,
  `creatAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
