server:
  port: 2020

spring:
  application:
    name: client-server
  thymeleaf:
      suffix: .html
      mode: LEGACYHTML5
#      mode: HTML5
      encoding: UTF-8
      content-type: text/html; charset=utf-8
      cache: false
  datasource:
    druid:
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      user:
        url: jdbc:mysql://client-mysql:3306/user?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
        username: root
        password: adminadmin
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 100
        max-wait: 10000
        min-idle: 10
        validation-query: SELECT 1
        test-on-borrow: true
        test-while-idle: true
        time-between-eviction-runs-millis: 5000
        min-evictable-idle-time-millis: 60000
      trade:
        url: jdbc:mysql://client-mysql:3306/trade?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
        username: root
        password: adminadmin
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 100
        max-wait: 10000
        min-idle: 10
        validation-query: SELECT 1
        test-on-borrow: true
        test-while-idle: true
        time-between-eviction-runs-millis: 5000
        min-evictable-idle-time-millis: 60000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


